site_name: "Werk24"
site_description: "Werk24 Client and API documentation"
site_author: "Dr. Jochen Mattes"

copyright: "Copyright &copy; 2020 Werk24"

nav:
  - GETTING STARTED:
      - Welcome: index.md
      - Basic Concepts: getting_started/basic_concepts.md
  - TUTORIALS:
      - Thumbnails: tutorials/thumbnails.md

  - ASKS:
      - Basics: asks/basics.md
      - Page / Thumbnail: asks/page_thumbnail.md
      - Sheet / Thumbnail: asks/sheet_thumbnail.md
      - Canvas / Thumbnail: asks/canvas_thumbnail.md
      - Variant / Measures: asks/variant_measures.md

  - MODELS:
      - W24Measure: models/w24measure.md
      - W24MeasureLabel: models/w24measure_label.md
      - W24Size: models/w24size.md
      - W24SizeTolerance: models/w24size_tolerance.md
    
  - CLI:
      - Basic: cli/basic.md
      - Techread: cli/techread.md
theme:
  name: "material"
  palette:
    primary: "black"
    accent: "blue"
  language: "en"
  feature:
    tabs: true
  # sticky_navigation: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.md_in_html



plugins:
  - mermaid2
  - search

extra_javascript:
  - https://unpkg.com/mermaid@8.4.8/dist/mermaid.core.js
  - matomoto.js

extra_css:
  - extra.css

extra:
  search:
    language: "en, de"

repo_name: "werk24"
