site_name: "Werk24"
site_description: "Werk24 Client and API documentation"
site_author: "Dr. Jochen Mattes"

copyright: "Copyright &copy; 2020 Werk24"

nav:
  - HOME: index.md
  - BASICS:
      - Getting Started: basics/quickstart.md
      - Service Times: basics/service_times.md
      - Authentication: basics/authentication.md
  - CLI:
      - Basic: cli/basic.md
      - Techread: cli/techread.md
  - API:
      - Getting Started: api/basics.md
      - TechreadClient: api/techread-client.md
      - Asks: api/asks.md
theme:
  name: "material"
  palette:
    primary: "blue-grey"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  # logo: "images/logo.png"
  feature:
    tabs: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - markdownmermaid

extra_javascript:
  - https://unpkg.com/mermaid@8.4.8/dist/mermaid.core.js
