site_name: "Werk24"
site_description: "Werk24 Client and API documentation"
site_author: "Dr. Jochen Mattes"

copyright: "Copyright &copy; 2020 Werk24"

nav:
  # - HOME:
  - HOME:
      - Welcome: index.md
      - Getting Started: basics/quickstart.md
      - Authentication: basics/authentication.md
  - CLI:
      - Basic: cli/basic.md
      - Techread: cli/techread.md
  - API:
      - Getting Started: api/basics.md
      - TechreadClient: api/techread-client.md
  - Asks:
      - Basics: asks/basics.md
      - Pages and Sheets: asks/page.md
      - Sectionals: asks/sectional.md
      - Variants and Measures: asks/variant.md
theme:
  name: "material"
  palette:
    primary: "black"
    accent: "pink"
  language: "en"
  feature:
    tabs: false
  # sticky_navigation: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.md_in_html



plugins:
  - markdownmermaid
  - search

extra_javascript:
  - https://unpkg.com/mermaid@8.4.8/dist/mermaid.core.js
  - matomoto.js

extra_css:
  - extra.css

extra:
  search:
    language: "en, de"

repo_name: "werk24"
